name: Update compendium
on:
  push:
      branches:
        - master
      paths:
        - db/totk/data/compendium/*.json
  workflow_dispatch:
jobs:
  main:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo npm install -g @rockset/cli
      - name: Authorize access
        run: |
          rockset auth:add me ${{ secrets.RS2_TOKEN }}
      - name: Add docs
        run: |
          cd db/totk/scripts
          sh update-compendium.sh